version: '3.1'

services:
  php:
    image: configs/php-${PHP}
    build:
      context: configs/php-${PHP}
      args:
        BUILDDEPS: ${BUILDDEPS}
        MODULES: ${MODULES}
    volumes:
      - ./src:/var/www/html

  web:
    image: nginx:latest
    ports:
      - ${PORT}:80
    volumes:
      - ./configs/nginx.template:/etc/nginx/conf.d/nginx.template
      - ./src:/var/www/html:delegated
      - ./logs:/var/log/nginx
    links:
      - php
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
